modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/FireBall1725/minicoal2/issues"
license="GNU GENERAL PUBLIC LICENSE"

[[mods]]
modId="minicoal2"
version="{{version}}"
displayName="MiniCoal 2"
displayURL="https://github.com/FireBall1725/minicoal2"
credits="Original mod by KiwiFails, ported and maintained by FireBall1725"
authors="KiwiFails, FireBall1725"
description="MiniCoal2 is a tiny mod that adds mini coal and charcoal that each will smelt 1 item."

[[dependencies.minicoal2]]
  modId="forge"
  mandatory=true
  versionRange="[28,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.minicoal2]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.16,]"
  ordering="NONE"
  side="BOTH"
